Add ynh_add_config helper
YunoHost/yunohost pull request #1055
Opened 2020-09-20 18:04 UTC by alexAubin

## The problem

Too much madness about ynh_replace_string all over the place, lack of consistent/simple template format/helpers

## Solution

Add yalh's experimental helper ynh_add_config into the core

## PR Status

Yolocomitted, but done I guess ? 

## How to test

Uuuh idk

2020-09-20 18:28 UTC, ericgaspar commented on data/helpers.d/utils
> +#
```suggestion
#   __YNH_NODE_LOAD_PATH__"    by $ynh_node_load_PATH
```

2020-09-20 18:30 UTC, ericgaspar reviewed
as it is also in the script... idk

2020-09-20 18:50 UTC, ericgaspar requested changes
Sorry for the review en deux temps :s

2020-09-20 18:50 UTC, ericgaspar commented on data/helpers.d/utils
> +#   __YNH_NODE_LOAD_PATH__"    by $ynh_node_load_PATH
```suggestion
#   __PATH__                by $path_url
#   __NAME__                by $app
#   __NAMETOCHANGE__        by $app
#   __USER__                by $app
#   __FINALPATH__           by $final_path
#   __PHPVERSION__          by $YNH_PHP_VERSION
#   __YNH_NODE_LOAD_PATH__  by $ynh_node_load_PATH
#
```

2020-09-20 18:50 UTC, ericgaspar commented on data/helpers.d/utils
> +#
```suggestion
#   __PATH__                by $path_url
#   __NAME__                by $app
#   __NAMETOCHANGE__        by $app
#   __USER__                by $app
#   __FINALPATH__           by $final_path
#   __PHPVERSION__          by $YNH_PHP_VERSION
#   __YNH_NODE_LOAD_PATH__  by $ynh_node_load_PATH
#
```

2020-09-22 10:18 UTC, zamentur approved these changes
LGTM

2020-09-24 19:25 UTC, merged