Fix typo (indefinite article in plural)
YunoHost/yunohost pull request #1470
Opened 2022-06-12 20:54 UTC by jose1711

## The problem
Just a minor typo/grammar problem.

## Solution
Drop indefinite article ("a").

2022-06-14 20:32 UTC, tituspijean approved these changes

2022-06-21 21:27 UTC, ericgaspar commented on src/utils/legacy.py
> +                r"/!\ Packagers ! This app uses very old deprecated helpers ... Yunohost automatically patched the helpers to use the new recommended practice, but please do consider fixing the upstr
```suggestion
                r"/!\ Packagers! This app uses very old deprecated helpers... YunoHost automatically patched the helpers to use the new recommended practice, but please do consider fixing the upstream code right now..."
```

2022-06-21 21:28 UTC, ericgaspar requested changes

2022-06-21 21:28 UTC, ericgaspar commented on src/utils/legacy.py
> +                r"/!\ Packagers ! This app uses very old deprecated helpers ... Yunohost automatically patched the helpers to use the new recommended practice, but please do consider fixing the upstr
```suggestion
                r"/!\ Packagers! This app uses very old deprecated helpers... YunoHost automatically patched the helpers to use the new recommended practice, but please do consider fixing the upstream code right now..."
```

2022-06-21 21:30 UTC, merged