Deny PRs where shfmt doesn't pass
YunoHost/yunohost pull request #1941
Opened 2024-08-30 17:28 UTC by selfhoster1312

Hopefully this should fail as the scripts don't pass. This is just an initial attempt i haven't checked that the CI syntax is good... Wait for it ! :)

2024-08-30 17:40 UTC, selfhoster1312 commented
Ready for review

2024-08-30 21:11 UTC, selfhoster1312 commented
So with the new helpers you can do:

- `just check`, `just pre-commit`, or `just lint`
- `make check`
- `./maintenance/pre-commit-check.sh`
- `act`

The last option, act, will setup something that's really close to a Github CI runner and run the actual tests through docker. That's the entire concept and power of [act](https://github.com/nektos/act) and it's great!

The first 3 options require that `shfmt` is already setup. It's been available since like forever in distro repositories. The second option requires `act` which can be setup in multiple ways including one that's as simple as `nix shell -p act`, as long as you already have docker/podman running.

I think that's already quite a few options and i'm happy to document them. Feedback is welcome.

2024-08-31 09:25 UTC, Salamandar requested changes

2024-08-31 09:25 UTC, Salamandar commented on maintenance/pre-commit-check.sh
> +set -e
```suggestion
#!/usr/bin/env bash
set -Eeuo pipefail
```

No space in shebang ; add some more error handling options.

2024-08-31 09:25 UTC, Salamandar commented on maintenance/pre-commit-check.sh
> +shfmt -bn -i 4 -d hooks/*
```suggestion
shfmt -sr -bn -i 4 -d helpers/helpers
shfmt -sr -bn -i 4 -d helpers/helpers.v2.1.d/*
shfmt -sr -bn -i 4 -d helpers/helpers.v2.d/*
shfmt -sr -bn -i 4 -d hooks/*
```
Add `-sr`. This option adds a space after file redirection carrets, so it creates for example this diff:

```
-    _generate_config >${pending_dir}/etc/yunohost/mdns.yml
+    _generate_config > ${pending_dir}/etc/yunohost/mdns.yml
```

2024-08-31 09:25 UTC, Salamandar commented on maintenance/pre-commit-check.sh
> +shfmt -bn -i 4 -d hooks/*
```suggestion
shfmt -sr -bn -i 4 -d helpers/helpers
shfmt -sr -bn -i 4 -d helpers/helpers.v2.1.d/*
shfmt -sr -bn -i 4 -d helpers/helpers.v2.d/*
shfmt -sr -bn -i 4 -d hooks/*
```
Add `-sr`. This option adds a space after file redirection carrets, so it creates for example this diff:

```
-    _generate_config >${pending_dir}/etc/yunohost/mdns.yml
+    _generate_config > ${pending_dir}/etc/yunohost/mdns.yml
```

2024-08-31 09:26 UTC, Salamandar commented on hooks/conf_regen/10-apt
> +    echo "deb https://packages.sury.org/php/ $(lsb_release --codename --short) main" >"${pending_dir}/etc/apt/sources.list.d/extra_php_version.list"
Actually this is handled by the `-sr` argument to shfmt, so that's good. Please don't manually fix that, just let shfmt run again ;)

2024-08-31 09:27 UTC, Salamandar commented on maintenance/pre-commit-check.sh
> +shfmt -bn -i 4 -d hooks/*
Crap, bad network -> duplicate comments

2024-08-31 10:22 UTC, merged

2024-08-31 10:27 UTC, Salamandar commented
Thank you @selfhoster1312 <3 For the rest of your commits I pushed the `shfmt_action` branch, you can open a PR yourself if you want :)