Improve LDAP performances when updating records, especially when many user entries exists
YunoHost/yunohost pull request #1975
Opened 2024-10-21 16:40 UTC by zamentur

## The problem

With 150 users and 12 apps, a `yunohost user create` take 1min
With 350 users and ~25 apps, a `yunohost user create` take hours maybe days.

## Solution

Replace `ldap.modlist.modifyModlist` by an optimize code that work for yunohost.

Test in a dev platforme (with ssd 600Mbps) : the 169th user creation is made in ~3s.

## PR Status

Need more test to be sure it doesn't break something...

## How to test

```
for i in {1..150}; do echo $i; yunohost user test$i -d ynh.local -F "test test" -p "Thisisadummypa:ssw0rd"; done
```

2024-10-21 17:32 UTC, Salamandar requested changes

2024-10-21 17:32 UTC, Salamandar commented on src/utils/ldap.py
> +        # Previously, we used modifyModlist, which directly uses the lib system libldap
Wouldn't it be more readable to split it into a function, named like `ldif_modifyModlist_finegrained` ?

2024-10-21 17:32 UTC, Salamandar commented on src/utils/ldap.py
> +                    if isinstance(value, set):
This test is useless (python will do it anyways when casting), you can just pass `list(value)` to the ldif method. Same line 275.

2024-10-23 09:56 UTC, Salamandar commented
Not sure about your last commits on `[user]` -> `user`, but apart from that, LGTM.

2024-10-23 09:56 UTC, Salamandar approved these changes

2025-01-20 14:12 UTC, alexAubin commented on conf/slapd/permission.ldif
> +  EQUALITY caseExactMatch
Did you end up having to perform an LDAP scheme migration for this or is it automagically handled by the regenconf ?

2025-01-20 14:12 UTC, alexAubin commented on src/settings.py
> +                {"sudoOption": "!authenticate" if passwordless_sudo else set()},
Sooo does this mean now the code magically handle the case where the data is a string (and won't interpret a string as a list of char) ?

2025-01-20 19:41 UTC, alexAubin commented on src/user.py
> +                user["mail"].remove(mail)
Not sure to fully understand that bit but my brain is not super fresh right now

2025-01-20 19:41 UTC, alexAubin commented on src/user.py
> +                continue
Also not sure to understand this bit

2025-01-20 19:41 UTC, alexAubin commented on src/user.py
> +        ).strip()
There are similar stuff in `portal.py`'s `portal_update()` that need to be adapted too

2025-01-20 19:41 UTC, alexAubin commented on src/user.py
> +            new_attr_dict["objectClass"].update({"mailGroup"})
```suggestion
            new_attr_dict["objectClass"].add("mailGroup")
```

2025-01-29 01:06 UTC, zamentur commented
Tests are ok on my local setup, but on the CI `systemctl is-active yunohost-portal-api >/dev/null` return 768 instead of 0 code...

@alexAubin @Axolotle : Is it possible that SSE and work on moulinette could have triggered this error ?

2025-02-18 21:49 UTC, alexAubin commented on src/utils/ldap.py
> +            value = {value}
```suggestion
            value = set(value)
```

2025-02-22 15:05 UTC, alexAubin commented on src/utils/ldap.py
> +            value = {value}
Stupid graphic bug hide the "commit this suggestion" button ufwuf zgvlbf ?

2025-02-22 16:15 UTC, merged