Shellcheck : Fix hooks/
YunoHost/yunohost pull request #2017
Opened 2024-12-16 17:49 UTC by Salamandar

2025-01-29 22:20 UTC, zamentur requested changes
nginx error on adding domain shoudl be fixed before merging

2025-01-29 22:20 UTC, zamentur commented on hooks/backup/50-conf_manually_modified_files
> +# shellcheck source=../../helpers/helpers
o_O

2025-01-29 22:20 UTC, zamentur commented on hooks/conf_regen/06-slapd
> +        curr_backend=$(grep '^database' /etc/ldap/slapd.conf | awk '{print $2}')
Is there a reason to remove the `2> /dev/null` ?

2025-01-29 22:20 UTC, zamentur commented on hooks/conf_regen/06-slapd
> +        if [ "$curr_backend" != 'mdb' ]; then
What if $curr_backend is empty string `""` ? Are you sure it secure to remove `[ -n "$curr_backend" ]`
```suggestion
        if [ "$curr_backend" != 'mdb' ] && [ -n "$curr_backend" ]; then
```

2025-01-29 22:20 UTC, zamentur commented on hooks/conf_regen/06-slapd
> +        curr_backend=$(grep '^database' /etc/ldap/slapd.conf | awk '{print $2}')
```suggestion
        curr_backend=$(grep '^database' /etc/ldap/slapd.conf 2> /dev/null | awk '{print $2}')
```

2025-01-29 22:20 UTC, zamentur commented on hooks/conf_regen/15-nginx
>  set -e
Test seems to fail for regenconf nginx, so may be that's why we keep only set -e ?

2025-01-29 22:21 UTC, zamentur commented on hooks/backup/50-conf_manually_modified_files
> +# shellcheck source=../../helpers/helpers
I don't understand if it's really needed to add `shellcheck source=../../helpers/helpers`

2025-03-01 11:32 UTC, Salamandar commented on hooks/backup/50-conf_manually_modified_files
> +# shellcheck source=../../helpers/helpers
The linter doesn't understand what `source /usr/share/yunohost/helpers` means: we usually don't develop on our yunohost machines.
We need to tell shellcheck where to find the helpers, and that is a relative path to the current file.

2025-03-01 11:39 UTC, Salamandar commented on hooks/conf_regen/06-slapd
> +        if [ "$curr_backend" != 'mdb' ]; then
I think this can't happen: the "grep" would fail. and the script would exit. But I'm not sure.

2025-03-08 10:40 UTC, merged