Remove legacy settings
YunoHost/yunohost pull request #935
Opened 2020-04-16 15:23 UTC by Josue-T

## The problem

Too many code to manage for old settings protected_uris, unprotected_uris, skipped_uris.

## Solution

Migrate all settings, to some permissions

## PR Status

Just tested qui unit test and it pass. It fail on the here probably because there still need some migrations.

## How to test

Checkout the branch. Try to install some app legacy app and see that some permission are made for the legacy settings.

## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

2020-04-19 16:37 UTC, Aeris1One commented
Will this PR remove compatibility with apps that does not migrated yet to new permission system ? (Those which always uses protected_uris, unprotected_uris, skipped_uris)

2020-04-20 09:55 UTC, Josue-T commented
> Will this PR remove compatibility with apps that does not migrated yet to new permission system ? (Those which always uses protected_uris, unprotected_uris, skipped_uris)

No we try to keep the compatibility for most of cases.

2020-04-22 20:04 UTC, Josue-T commented
Hello,

Made some tests with this following apps:
- wordpress
- nextcloud
- gitea
- etherpad_mypads
- leed

I found some regression and some bug which are now fixed. So I think it should be OK to go forward with this.

2020-09-15 20:20 UTC, ericgaspar requested changes

2020-09-15 20:20 UTC, ericgaspar commented on locales/en.json
>      "migration_0019_migration_failed_trying_to_rollback": "Could not migrate… trying to roll back the system.",
```suggestion
    "migration_0019_migration_failed_trying_to_rollback": "Unable to migrate... trying to roll back the system.",
```

2020-09-16 17:01 UTC, alexAubin commented
Copypasta of [this comment](https://github.com/YunoHost/yunohost/pull/861#issuecomment-693529756) : 

Follow-up of yesterday's discussion about non-trivial legacy permissions. Here's a dump of what exists in the wild (only apps declared as working) : 

https://drop.devloprog.org/r/kep83fHuY_#kPT86CnRL7Zf7eqqyvNZflfT4DHRgO2Q/GmKC71do7k=

![2020-09-16-184735_1366x768_scrot](https://user-images.githubusercontent.com/4533074/93367706-2713ca00-f84d-11ea-9027-c11ce4ff6541.png)

2020-09-24 19:49 UTC, alexAubin commented
Soooo following the previous small study, and as a solution to the issue of "what do with non-trivial legacy permissions" I'm proposing this commit https://github.com/YunoHost/yunohost/pull/935/commits/2b4e14cca7b27ce21a88d18de290671015149f67 that hard-code a small description of what the uri/regexes correspond to ...

I'm far from being 100% sure about the exactitude of the info though ... (in fact im ~sure about only ~50ish% or these) but at least we can discuss the principle and iterate on the names if you have some more insight

2020-09-27 16:03 UTC, alexAubin commented
Sooooo uh idk, proposing to merge this PR into permission_protection and keep the discussion going there ? It looks to me that this PR is the right way to go and we just need to clarify some implementation details about it, which can be done in the other PR (and will allow easier testing and iteration)

2020-09-30 15:06 UTC, alexAubin commented
Let's-a-go then o/

2020-09-30 15:06 UTC, merged